// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://mnmsqluz3vcqniyorkboy6g2rq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2ltrib7b6jew3nao7veuqv3e7e",
    "aws_content_delivery_bucket": "leboncoin-20190202154336-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://leboncoin-20190202154336-hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:589807f2-9f3d-44d4-baee-911b79e76540",
    "aws_cognito_region": "eu-west-1",
    "aws_mobile_analytics_app_id": "b3f0706b7cab42ce920ae436236d1a81",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
